<div id="pnl_edituploadgrid">
	<div class="fgta-page-title">Daftar Upload</div>
	<div id="pnl_edituploadgrid-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>

	<!--// Untuk keperluan search di detil
	<div id="pnl_edituploadgrid-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-item" style="width: 50px;">Cari</div>
			<div class="list-search-item">
				<input id="pnl_edituploadgrid-txt_search" class="easyui-textbox" style="width: 100%">
			</div>
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_edituploadgrid-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
	</div>	
	//-->

	<div style="margin-top: 10px; margin-bottom: 15px">
		<table id="pnl_edituploadgrid-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th type="check">chk</th>					
					<th mapping="medialogproofupload_id">medialogproofupload_id</th>
					<th mapping="mediaadslot_descr">mediaadslot_descr</th>
					<th mapping="actual_timestart">actual_timestart</th>
					<th mapping="actual_timeend">actual_timeend</th>
					<th mapping="actual_duration" style="text-align: right" formatter="row_format_number">actual_duration</th>
					<th mapping="spot_id">spot_id</th>
					<th mapping="agency_name">agency_name</th>
					<th mapping="advertiser_name">advertiser_name</th>
					<th mapping="brand_name">brand_name</th>
					<th mapping="programme_name">programme_name</th>
					<th mapping="episode_name">episode_name</th>
					<th mapping="medialogproof_validr" style="text-align: right" formatter="row_format_number">medialogproof_validr</th>
					<th mapping="medialogproof_ppnidr" style="text-align: right" formatter="row_format_number">medialogproof_ppnidr</th>

					<th mapping=""></th>
				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 30px; border-bottom: 1px solid #000000; text-align: center">*</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ID</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SlotDescr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ActualTimeStart</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ActualTimeEnd</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">ActualDuration</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SpotId</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">AgencyName</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">AdvertiserName</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">BrandName</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">ProgrammeName</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">EpisodeName</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Total IDR</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">PPN</td>
					<td class="fgtable-head" style="border-bottom: 1px solid #000000; text-align: center">&nbsp;</td>
				</tr>
			</thead>
		</table>
	</div>

	<div id="pnl_edituploadgrid-control" style="display: flex; justify-content: space-between; margin-bottom: 100px">
		<div>
			<a id="pnl_edituploadgrid-removechecked" href="javascript:void(0)" class="easyui-linkbutton c8">Hapus Checked</a>
		</div>

		<div>
			<a id="pnl_edituploadgrid-addrow" href="javascript:void(0)" class="easyui-linkbutton c8">Tambah Baris</a>
		</div>

		<div>
		</div>

	</div>


</div>	
