<?php require_once dirname(__FILE__).'/logproof-list.phtml' ?>
<?php require_once dirname(__FILE__).'/logproof-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/logproof-itemgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/logproof-itemform.phtml' ?>
<?php require_once dirname(__FILE__).'/logproof-uploadgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/logproof-uploadform.phtml' ?>



