<?php require_once dirname(__FILE__).'/mediaorder-list.phtml' ?>
<?php require_once dirname(__FILE__).'/mediaorder-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/mediaorder-itemsgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/mediaorder-itemsform.phtml' ?>
<?php require_once dirname(__FILE__).'/mediaorder-paytermgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/mediaorder-paytermform.phtml' ?>





<div id="pnl_edit_record_custom" style="display: none">
	<div class="form_row">
		<div class="form_label_col">Commit By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Commit Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-commitdate"></span>
		</div>
	</div>

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Completed Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-completeddate"></span>
		</div>
	</div>	

	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Billed Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-billdate"></span>
		</div>
	</div>	



	<div class="form_row" style="margin-top: 30px;">
		<div class="form_label_col">Close By</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-closeby"></span>
		</div>
	</div>	

	<div class="form_row">
		<div class="form_label_col">Close Date</div>
		<div class="form_input_col" style="border: 0px solid black">
			<span id="pnl_edit_record-closedate"></span>
		</div>
	</div>	
		
</div>