<div id="pnl_editprogform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div>Edit Program</div>
		<a id="pnl_editprogform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editprogform-title" style="margin-top: 0px; margin-bottom: 30px; font-weight: bold; font-size: 1.2em">XXXXXXX</div>


	<form id="pnl_editprogform-form">

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-txt_mediaschprog_id" class="easyui-textbox" mapping="mediaschprog_id" uppercase="true" maxlength="14"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'ID harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Mulai</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-txt_mediaschprog_timestart" class="easyui-textbox" mapping="mediaschprog_timestart" uppercase="true" maxlength="90"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Waktu Mulai harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Selesai</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-txt_mediaschprog_timeend" class="easyui-textbox" mapping="mediaschprog_timeend" uppercase="true" maxlength="90"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Waktu Selesai harus diisi' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-txt_mediaschprog_notes" class="easyui-textbox" mapping="mediaschprog_notes"  maxlength="90"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Program</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-cbo_mediaprog_id" class="easyui-combo" style="width: 400px" mapping="mediaprog_id" display="mediaprog_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Program harus diisi', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editprogform-cbo_mediaprog_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Schedule ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editprogform-txt_mediasch_id" class="easyui-textbox" mapping="mediasch_id"  maxlength="14"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editprogform-autoadd" type="checkbox"><label for="pnl_editprogform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editprogform-btn_save" class="easyui-linkbutton c1" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	



	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div>
			<a id="pnl_editprogform-btn_prev" class="easyui-linkbutton c8" style="width: 50px">Prev</a>
			<a id="pnl_editprogform-btn_next" class="easyui-linkbutton c8" style="width: 50px">Next</a>
		</div>

		<div>
			<a id="pnl_editprogform-btn_addnew" class="easyui-linkbutton c8" style="width: 100px">Tambah Baru</a>
		</div>

		<div>
			<a id="pnl_editprogform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>




</div>	
