<div id="pnl_list">
	<div class="fgta-page-title">Daftar Log Proof</div>

	<div id="pnl_list-pnl_head" style="display: flex; align-items: flex-end">
		<div class="list-buttonbaru" style="text-align: right; width: calc(100% - 10px); float: right;  position: absolute">
			<a href="javascript:void(0)" id="pnl_list-btn_new" class="easyui-linkbutton c8" style="width: 60px">Baru</a>
		</div>


		<!-- START: Query Box -->
		<div class="list-search-wrap" style="width: calc(100% - 65px); display: flex;">
			<div class="list-search-param" style="width: 280px">
				<div class="list-search-item" style="width: 50px; align-self:center; text-align: right">Periode</div>
				<div class="list-search-item" style="width: 200px">
					<input id="pnl_list-cbo_search_periode" class="easyui-combo" style="width: 100%">
				</div>
			</div>

			<div class="list-search-param" style="width: 100px">
				<select id="pnl_list-cbo_asigned" class="easyui-combobox" name="assigned" style="width:100px;">
					<option value="unassigned">UnAssigned</option>
					<option value="assigned">Assigned</option>
					<option value="all">ALL</option>
				</select>
			</div>	

			<div class="list-search-param" style="width: 180px">
				<div class="list-search-item" style="width: 50px;align-self:center; text-align: right">Cari</div>
				<div class="list-search-item" style="width: 100px">
					<input id="pnl_list-txt_search" class="easyui-textbox" style="width: 100%">
				</div>
			</div>
			
			<div class="list-search-item" style="width: 45px">
				<a href="javascript:void(0)" id="pnl_list-btn_load" class="easyui-linkbutton c8" style="width: 45px">Load</a>
			</div>
		</div>
		<!-- END: Query Box -->
	</div>


	<div style="margin-top: 10px">
		<table id="pnl_list-tbl_list" paging="true" cellspacing="0" width="100%" class="deftable">
			<thead>
				<tr>
					<th mapping="medialogproof_date">medialogproof_date</th>

					
					<th mapping="mediaadslot_descr">mediaadslot_descr</th>
					<th mapping="actual_timestart">actual_timestart</th>
					<th mapping="actual_timeend">actual_timeend</th>
					<th mapping="actual_duration" style="text-align: right"  formatter="row_format_number">actual_duration</th>
					<th mapping="spot_id">spot_id</th>
					<th mapping="mediaorder_descr">mediaorder_descr</th>

				</tr>
				<tr style="background-color: #cccccc; height: 30px">
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Date</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Descr</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Actual Mulai</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Selesai</td>
					<td class="fgtable-head" style="width: 100px; text-align: right; border-bottom: 1px solid #000000">Durasi</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">SpotId</td>
					<td class="fgtable-head" style="width: 100px; border-bottom: 1px solid #000000">Media Order</td>

				</tr>
			</thead>
		</table>
	</div>



</div>